### ISSUE TITLE
Update to node16 required

### ISSUE THREAD

**Issue by christoph-nimagna** [fbactions/setup-winsdk#36]
Github reports a warning when using this:

`The following actions uses node12 which is deprecated and will be forced to run on node16: fbactions/setup-winsdk@v1.3.0.`

Could you please update the workflow action?

**Comment by friederbluemle** [comment]
Hi @christoph-nimagna - Thanks for the report! New version will be available shortly!

**Comment by friederbluemle** [comment]
The new version should be available now. To be safe, I decided to move to `v2` with these changes (the first commits in the repo in over a year).

Could you test to see if everything works as expected? In your workflow file, change:

```diff
-- uses: fbactions/setup-winsdk@v1
+- uses: fbactions/setup-winsdk@v2
```

**Comment by christoph-nimagna** [comment]
@friederbluemle - works like a charm! Thanks for the swift fix and for maintaining this build action! 💪 🚀
