### ISSUE TITLE
Update to node.js 20

### ISSUE THREAD

**Issue by christoph-nimagna** [fbactions/setup-winsdk#44]
Using this action yields a warning about node.js 16 actions being deprecated.

Can you please update the action to use node.js 20?

**Comment by christoph-nimagna** [comment]
@friederbluemle - any update on this? node.js 16 is marked as deprecated.

**Comment by friederbluemle** [comment]
@christoph-nimagna - Thanks for the heads up, and apologies for the delay!
A new version was just released, the deprecation warning should be gone now.
